# Generated by Django 2.1.15 on 2020-03-26 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims.Album')),
            ],
        ),
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha1', models.CharField(max_length=40, unique=True)),
                ('photo', models.ImageField(upload_to='images')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('file_size', models.IntegerField()),
                ('origin_filename', models.CharField(max_length=255)),
                ('format', models.CharField(max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageToFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.CharField(max_length=10)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ims.ImageFile')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='files',
            field=models.ManyToManyField(through='ims.ImageToFile', to='ims.ImageFile'),
        ),
        migrations.AddField(
            model_name='image',
            name='md_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='md', to='ims.ImageFile'),
        ),
        migrations.AddField(
            model_name='image',
            name='origin_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin', to='ims.ImageFile'),
        ),
        migrations.AddField(
            model_name='image',
            name='sm_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sm', to='ims.ImageFile'),
        ),
        migrations.AddField(
            model_name='album',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ims.Category'),
        ),
        migrations.AddField(
            model_name='album',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='album',
            name='tags',
            field=models.ManyToManyField(blank=True, to='ims.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='imagetofile',
            unique_together={('image', 'shape')},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('owner', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='album',
            unique_together={('owner', 'title')},
        ),
    ]
