# Generated by Django 2.1.15 on 2020-03-31 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
