# Generated by Django 2.1.15 on 2020-03-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetofile',
            name='sharp',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='imagetofile',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='imagetofile',
            name='height',
        ),
        migrations.RemoveField(
            model_name='imagetofile',
            name='local_path',
        ),
        migrations.RemoveField(
            model_name='imagetofile',
            name='width',
        ),
        migrations.AlterUniqueTogether(
            name='imagetofile',
            unique_together={('image', 'file'), ('image', 'sharp')},
        ),
    ]
