# Generated by Django 2.1.15 on 2020-03-14 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0003_auto_20200314_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagetofile',
            old_name='sharp',
            new_name='shape',
        ),
        migrations.AlterUniqueTogether(
            name='imagetofile',
            unique_together={('image', 'file'), ('image', 'shape')},
        ),
    ]
