# Generated by Django 2.1.15 on 2020-03-14 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0004_auto_20200314_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='file_name',
        ),
        migrations.AddField(
            model_name='image',
            name='md_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='md', to='ims.ImageFile'),
        ),
        migrations.AddField(
            model_name='image',
            name='origin_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin', to='ims.ImageFile'),
        ),
        migrations.AddField(
            model_name='image',
            name='sm_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sm', to='ims.ImageFile'),
        ),
    ]
