# Generated by Django 2.1.15 on 2020-03-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0005_auto_20200314_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='format',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
