# Generated by Django 2.1.15 on 2020-03-17 12:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ims', '0006_imagefile_format'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='album',
            unique_together={('owner', 'title')},
        ),
    ]
