# Generated by Django 2.1.15 on 2020-03-20 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0007_auto_20200317_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='url',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ims.Category'),
        ),
    ]
