# Generated by Django 2.1.15 on 2020-03-22 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0009_auto_20200321_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='files',
            field=models.ManyToManyField(through='ims.ImageToFile', to='ims.ImageFile'),
        ),
        migrations.AlterField(
            model_name='imagetofile',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ims.ImageFile'),
        ),
        migrations.AlterUniqueTogether(
            name='imagetofile',
            unique_together={('image', 'shape')},
        ),
    ]
