language: python
python:
  - "3.6"
services:
  - docker
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
script: |
  python manage.py test
after_success:
  - codecov
