version: '3'
services:
  db:
    image: mariadb
    volumes:
      - database:/var/lib/mysql:rw
    restart: always
    networks:
      - private
    environment:
      MYSQL_ROOT_PASSWORD: changeyourstrongpasswordhere
      MYSQL_DATABASE: imagebank
      MYSQL_USER: imagebank
      MYSQL_PASSWORD: imagebankpass
  web:
    image: imagebank
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      #- ./static:/var/www/static:z
      - media:/var/www/media:Z
      #- ./logs:/code/logs:z
    environment:
      DJANGO_SETTINGS_MODULE: imagebank.prod_settings
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: imagebank
      DB_USER: imagebank
      DB_PASSWORD: imagebankpass
      #UWSGI_STATIC_MAP: "/static/=/var/www/static/;/images/=/var/www/media/"
      #UWSGI_HTTP: ":8000"
      #UWSGI_WSGI_FILE: "imagebank/wsgi.py"
    # command: uwsgi --static-map /static=/var/www/static --static-map /images=/var/www/media
    command: uwsgi imagebank/uwsgi.ini
    networks:
      - private

networks:
  private:
volumes:
  database:
  media:

